# This script generates a list of numbers that are powers of two, using binary shifting.
# Each number is generated by shifting 1 to the left by i positions, where i ranges from 0 to 999.


results = []
for i in range (1000):
    results.append(1<<i)

#write the results to a file
with open('binary_shifting_results.txt', 'w') as f:
    for num in results:
        f.write(f"{num}\n\n")

#print message to user that the file has been successfully written (if it has)
print("Results have been written to binary_shifting_results.txt")
